@url = http://localhost:8000/api
@token =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY1MjY5MzYsImV4cCI6MTc0NjUzMDUzNiwibmJmIjoxNzQ2NTI2OTM2LCJqdGkiOiI3UER6MVdyMzFSODkzT2NUIiwic3ViIjoiMyIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.2FIp4kjLMy8fB-tAeuw24YzEEHAvkVHeDEnCFNJn2Cw

###

### ➕ Create Course
POST {{url}}/courses/create
Content-Type: multipart/form-data
Accept: application/json
Authorization: Bearer {{token}}

{
    "title":"title",
    "description":"description",
    "category":"category",
    "instructor_id":"instructor id"
}
### Example for Postman or REST Client with file support:
# title: Laravel Basics
# description: Learn Laravel from scratch
# category: Backend
# instructor_id: 1
# pdfs: (file)
# videos: (file)

###

### 📦 Get All Courses
GET {{url}}/courses/find
Authorization: Bearer {{token}}
Accept: application/json

###

### 🔍 Get Course by ID
GET {{url}}/courses/1
Authorization: Bearer {{token}}
Accept: application/json

###

### 👨‍🏫 Get Courses by Instructor
GET {{url}}/courses/instructor?instructor_id=1
Authorization: Bearer {{token}}
Accept: application/json
Authorization: Bearer {{token}}
