@url = http://localhost:8000/api
@token =eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDg2MzY5MTUsImV4cCI6MTc1MTIyODkxNSwibmJmIjoxNzQ4NjM2OTE1LCJqdGkiOiJNc25GaDYxWGg1SlBTMmduIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.0cCYCS6qaAnHKeyy68961a7pl_Hj62LSijpJnQUGy_0



###

### ➕ Create Course
POST {{url}}/courses/create
Content-Type: multipart/form-data
Accept: application/json
Authorization: Bearer {{token}}

{
    "title":"title",
    "description":"description",
    "category":"category",
    "instructor_id":"instructor id"
}
### Example for Postman or REST Client with file support:
# title: Laravel Basics
# description: Learn Laravel from scratch
# category: Backend
# instructor_id: 1
# pdfs: (file)
# videos: (file)

###

### 📦 Get All Courses
GET {{url}}/courses/find
Authorization: Bearer {{token}}
Accept: application/json

###

### 🔍 Get Course by ID
GET {{url}}/courses/find/1
Authorization: Bearer {{token}}
Accept: application/json

###

### 👨‍🏫 Get Courses by Instructor
GET {{url}}/courses/find/instructor/1
Authorization: Bearer {{token}}
Accept: application/json
Authorization: Bearer {{token}}
