@url = http://localhost:8000/api/subscribe
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDg2MzY5MTUsImV4cCI6MTc1MTIyODkxNSwibmJmIjoxNzQ4NjM2OTE1LCJqdGkiOiJNc25GaDYxWGg1SlBTMmduIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.0cCYCS6qaAnHKeyy68961a7pl_Hj62LSijpJnQUGy_0


### 
POST {{url}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "cource_id":1,
    "price":66
}

###/student/{studentId}/courses
GET {{url}}/student/2/courses
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###/course/{courseId}/students
GET {{url}}/course/1/students
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###/course/{courseId}/students
GET {{url}}/analytics/1/students
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}