@url=http://localhost:8000/api
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDg2MDU2ODMsImV4cCI6MTc0ODYwOTI4MywibmJmIjoxNzQ4NjA1NjgzLCJqdGkiOiI3czl2YUFGQlNqcnRBSmlkIiwic3ViIjoiNCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.PQuAFqTIA0j3pIukV6-fmhl1Am1kF9CgE35yXQbMNEQ

### Register
POST {{url}}/auth/sign-up HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "std std",
  "email": "std@gmail.com",
  "password": "test12345",
  "role":"student"
  }

### Login
POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "admin@gmail.com",
  "password": "test12345"
}

### get users
GET {{url}}/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
