@url=http://localhost:8000/api
@token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3NDY1MjY1OTMsImV4cCI6MTc0NjUzMDE5MywibmJmIjoxNzQ2NTI2NTkzLCJqdGkiOiJIdlZkVVFyZlNwSnJXRUwwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.LU8K26hzrudj0MeRYfoAEf130cODvw9L9nC-VL43alM

### Register
POST {{url}}/auth/sign-up HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "instructor",
  "email": "instructor@gmail.com",
  "password": "test12345",
  "role":"instructor"
  }

### Login
POST {{url}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "student@gmail.com",
  "password": "test12345"
}

### get users
GET {{url}}/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
